import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('./feedback.js',import.meta.url),'utf8');
function harness(){const ctx=vm.createContext({draft:{ratings:{},added:[],strokes:[]},undo:[[],[],[]],redo:[[],[],[]],step:0,beforeAction:null,pointer:null,original:false,preview:null,hover:null,fields:['ratings','added','strokes'],clone:x=>JSON.parse(JSON.stringify(x)),localSave(){},render(){},status(){}});vm.runInContext(source.slice(source.indexOf('function beginAction()'),source.indexOf('function distance')),ctx);return ctx;}
test('undo and redo restore a whole gesture; no-op keeps redo, new edit clears it',()=>{const c=harness();vm.runInContext("beginAction();draft.ratings={a:'red',b:'blue'};commitAction('ratings');historyAction('undo');",c);assert.equal(Object.keys(c.draft.ratings).length,0);assert.equal(c.redo[0].length,1);vm.runInContext("beginAction();commitAction('empty click');",c);assert.equal(c.redo[0].length,1);vm.runInContext("historyAction('redo');",c);assert.equal(c.draft.ratings.b,'blue');vm.runInContext("historyAction('undo');beginAction();draft.ratings.c='neutral';commitAction('new rating');",c);assert.equal(c.redo[0].length,0);});
test('undo history is isolated per step; redo rebuild does not alter ratings',()=>{const c=harness();vm.runInContext("beginAction();draft.ratings.a='red';commitAction('rating');step=1;beginAction();draft.added.push({x1:50,y1:50,x2:150,y2:50});commitAction('placement');historyAction('undo');",c);assert.equal(c.draft.added.length,0);assert.equal(c.draft.ratings.a,'red');vm.runInContext("historyAction('redo');",c);assert.equal(c.draft.added.length,1);vm.runInContext("step=0;historyAction('undo');",c);assert.equal(c.draft.added.length,1);assert.equal(Object.keys(c.draft.ratings).length,0);});
test('grid pieces snap to intersections, rotate and cannot extend outside the canvas',()=>{const c=vm.createContext({orientation:'horizontal',pieceLength:100,pieces:{horizontal:[1,0],vertical:[0,1],rising:[1,-1],falling:[1,1]}});vm.runInContext(source.slice(source.indexOf('function stamp('),source.indexOf('function paint(')),c);assert.equal(vm.runInContext('stamp({x:128,y:74}).x1',c),150);assert.equal(vm.runInContext('stamp({x:1199,y:100})',c),null);vm.runInContext("orientation='rising'",c);assert.equal(vm.runInContext('stamp({x:100,y:50})',c),null);assert.equal(vm.runInContext('stamp({x:100,y:150}).y2',c),50);});

test('removing and restoring originals preserves ratings and is undoable with added sticks',()=>{const c=harness();vm.runInContext("draft.ratings={a:'blue',b:'red'};step=1;beginAction();draft.rebuildRemoved=['a'];commitAction('remove');historyAction('undo');",c);assert.equal(c.draft.rebuildRemoved.length,0);assert.equal(c.draft.ratings.a,'blue');vm.runInContext("historyAction('redo');beginAction();draft.rebuildRestored=['b'];commitAction('restore');historyAction('undo');",c);assert.equal(c.draft.rebuildRemoved[0],'a');assert.equal(c.draft.rebuildRestored.length,0);assert.equal(c.draft.ratings.b,'red');});
test('rebuild removals depend only on explicit choices, never rating colors',()=>{const c=vm.createContext({draft:{ratings:{a:'red',b:'blue',c:'red'},rebuildRemoved:['b'],rebuildRestored:['a']}});vm.runInContext(source.slice(source.indexOf('function removedIds()'),source.indexOf('const palette=')),c);assert.equal(vm.runInContext('removedIds().sort().join(",")',c),'b');vm.runInContext('draft.rebuildRemoved=[]',c);assert.equal(vm.runInContext('removedIds().length',c),0);});

test('comment edits and deletion undo as a unit without affecting bridge ratings',()=>{const c=harness();vm.runInContext("fields[2]='annotations';step=2;draft.annotations=[];draft.ratings={a:'blue'};beginAction();draft.annotations=[{id:'pin',x:120,y:240,color:'red',text:'Needs a railing'}];commitAction('comment');beginAction();draft.annotations[0].color='some';draft.annotations[0].text='Railing needs to be higher';commitAction('edit');historyAction('undo');",c);assert.equal(c.draft.annotations[0].text,'Needs a railing');assert.equal(c.draft.annotations[0].color,'red');vm.runInContext("historyAction('redo');beginAction();draft.annotations=[];commitAction('delete');historyAction('undo');",c);assert.equal(c.draft.annotations[0].text,'Railing needs to be higher');assert.equal(c.draft.ratings.a,'blue');});
