import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const source=fs.readFileSync(new URL('./feedback.js',import.meta.url),'utf8');
function harness(){const ctx=vm.createContext({draft:{ratings:{},added:[],strokes:[]},undo:[[],[],[]],redo:[[],[],[]],step:0,beforeAction:null,pointer:null,original:false,preview:null,hover:null,fields:['ratings','added','strokes'],clone:x=>JSON.parse(JSON.stringify(x)),localSave(){},render(){},status(){}});vm.runInContext(source.slice(source.indexOf('function beginAction()'),source.indexOf('function distance')),ctx);return ctx;}
test('undo and redo restore a whole gesture; no-op keeps redo, new edit clears it',()=>{const c=harness();vm.runInContext("beginAction();draft.ratings={a:'red',b:'blue'};commitAction('ratings');historyAction('undo');",c);assert.equal(Object.keys(c.draft.ratings).length,0);assert.equal(c.redo[0].length,1);vm.runInContext("beginAction();commitAction('empty click');",c);assert.equal(c.redo[0].length,1);vm.runInContext("historyAction('redo');",c);assert.equal(c.draft.ratings.b,'blue');vm.runInContext("historyAction('undo');beginAction();draft.ratings.c='neutral';commitAction('new rating');",c);assert.equal(c.redo[0].length,0);});
test('undo history is isolated per step; redo rebuild does not alter ratings',()=>{const c=harness();vm.runInContext("beginAction();draft.ratings.a='red';commitAction('rating');step=1;beginAction();draft.added.push({x1:50,y1:50,x2:150,y2:50});commitAction('placement');historyAction('undo');",c);assert.equal(c.draft.added.length,0);assert.equal(c.draft.ratings.a,'red');vm.runInContext("historyAction('redo');",c);assert.equal(c.draft.added.length,1);vm.runInContext("step=0;historyAction('undo');",c);assert.equal(c.draft.added.length,1);assert.equal(Object.keys(c.draft.ratings).length,0);});
test('grid pieces snap to intersections, rotate and cannot extend outside the canvas',()=>{const c=vm.createContext({orientation:'horizontal',pieceLength:100,pieces:{horizontal:[1,0],vertical:[0,1],rising:[1,-1],falling:[1,1]}});vm.runInContext(source.slice(source.indexOf('function stamp('),source.indexOf('function paint(')),c);assert.equal(vm.runInContext('stamp({x:128,y:74}).x1',c),150);assert.equal(vm.runInContext('stamp({x:1199,y:100})',c),null);vm.runInContext("orientation='rising'",c);assert.equal(vm.runInContext('stamp({x:100,y:50})',c),null);assert.equal(vm.runInContext('stamp({x:100,y:150}).y2',c),50);});
